name: Basic libao configuration for macOS with BREW -- classic only, because macOS can't host NQPTP.

on:
  workflow_dispatch:
  push:
    branches: [ "development", "danger" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        brew install automake
        brew install popt
        brew install libconfig
        brew install libao

    - name: Configure
      run: |
        autoreconf -fi
        ./configure --with-os=darwin --with-ao --with-stdout --with-dns_sd --with-ssl=openssl
    
    - name: Make
      run: |
        make
